[package]
name = "motd"
version = "0.1.0"
authors = ["Kevin Allison <kvnallsn@gmail.com>"]
edition = "2018"

[dependencies]
chrono ="0.4"
clap = "2.33"
fern = "0.5"
log = "0.4"
pnet_datalink = "0.22"
regex = "1"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
